name: CI

on:
  # schedule:
    # - cron: '0 0 * * *' # Test once a day
  workflow_dispatch:

jobs:
  test-fresh:
    strategy:
      matrix:
        smalltalk:
          - Squeak64-Trunk
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: marceltaeumel/setup-smalltalkCI@marceltaeumel/install-path
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: printenv
        shell: bash
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        continue-on-error: false
        shell: bash
        timeout-minutes: 15
      # - name: Setup tmate debugging session
      #   uses: mxschmitt/action-tmate@v3



# /c/Users/runneradmin/.smalltalkCI

  # test-existing:
  #   needs: [phase-fresh]