name: CI

on:
  # schedule:
    # - cron: '0 0 * * *' # Test once a day
  workflow_dispatch:

jobs:
  test-fresh:
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Squeak64-Trunk
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up SmalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      # - run: |
      #     echo $SMALLTALK_CI_HOME
      #     echo $SMALLTALK_CI_VMS
      #   shell: bash
      - run: printenv
        shell: bash
      - name: Download Latest OpenSmalltalk VM
        shell: bash
        run: ./prepare_vm.sh
        env:
          CONFIG_SMALLTALK: ${{ matrix.smalltalk }}
      - name: Run Tests
        shell: bash
        run: smalltalkci -s ${{ matrix.smalltalk }} --vm ${{ env.VM_FILEPATH }}
        timeout-minutes: 15
      # - name: Setup tmate debugging session
      #   uses: mxschmitt/action-tmate@v3

# env.SMALLTALK_CI_HOME

# /c/Users/runneradmin/.smalltalkCI

  # test-existing:
  #   needs: [phase-fresh]