name: CI

on:
  # schedule:
    # - cron: '0 0 * * *' # Test once a day
  workflow_dispatch:

jobs:
  test-fresh:
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Squeak64-Trunk
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      CONFIG_SMALLTALK: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up SmalltalkCI
        # uses: hpi-swa/setup-smalltalkCI@v1
        uses: marceltaeumel/setup-smalltalkCI@marceltaeumel/install-path
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          smalltalkCI-workspace: ${{ github.workspace }}
      - name: Download Latest OpenSmalltalk VM
        shell: bash
        run: ./prepare_vm.sh
        
      - name: Run Tests
        continue-on-error: true # To also do second phase
        shell: bash
        run: smalltalkci --smalltalk ${{ matrix.smalltalk }} --vm ${{ env.VM_FILEPATH }}
        timeout-minutes: 15

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            .smalltalkCI/_builds/*.sources
            .smalltalkCI/_builds/*.st
            .smalltalkCI/_builds/*.image
            .smalltalkCI/_builds/*.changes
          # ${{ env.SMALLTALK_CI_BUILD }}/* absolute path does not work on Windows

      # - name: Setup tmate debugging session
      #   uses: mxschmitt/action-tmate@v3

  test-existing:
    needs: [test-fresh]
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Squeak64-Trunk
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        artifact:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    if: ${{ matrix.artifact }} != ${{ matrix.os }}
    env:
      CONFIG_SMALLTALK: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up SmalltalkCI
        # uses: hpi-swa/setup-smalltalkCI@v1
        uses: marceltaeumel/setup-smalltalkCI@marceltaeumel/install-path
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          smalltalkCI-workspace: ${{ github.workspace }}

      - name: Download Latest OpenSmalltalk VM
        shell: bash
        run: ./prepare_vm.sh

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with: # all artifacts
          name: ${{ matrix.artifact }}
          path: .smalltalkCI/_builds
          # ${{ env.SMALLTALK_CI_BUILD_BASE }} is not working on Windows

      # - name: Run Tests
      #   shell: bash
      #   run: ./test_image.sh

      - name: Run Tests (.image from ${{ matrix.artifact }})
        continue-on-error: false
        shell: bash
        run: smalltalkci --smalltalk ${{ matrix.smalltalk }} --vm ${{ env.VM_FILEPATH }} --image "${{ env.SMALLTALK_CI_BUILD_BASE}/TravisCI.image"
        timeout-minutes: 15
